Vagrant.configure("2") do |config|

  # --- K3s Agent ---
  config.vm.define "k3s-agent" do |agent|
    agent.vm.box = "bento/debian-11"
    agent.vm.hostname = "k3s-agent"
    agent.vm.box_version = "202508.03.0"

    agent.vm.network "public_network",
      bridge: "Vmnet0" ,
      ip: "192.168.100.101",
      netmask: "255.255.255.0"
    agent.vm.network "private_network", ip: "192.168.20.10"

    agent.vm.provider "vmware_desktop" do |vm|
      vm.cpus = "2"
      vm.memory = "6144"
    end
  end

  # --- K3s Server ---
  config.vm.define "k3s-controlplane" do |controlplane|
    controlplane.vm.box = "bento/debian-11"
    controlplane.vm.hostname = "k3s-controlplane"
    controlplane.vm.box_version = "202508.03.0"

    controlplane.vm.network "public_network",
      bridge: "Vmnet0" ,
      ip: "192.168.100.100",
      netmask: "255.255.255.0"

    controlplane.vm.network "private_network", ip: "192.168.20.11"
  
    controlplane.vm.provider "vmware_desktop" do |vm|
      vm.cpus = "2"
      vm.memory = "4096"
    end
  end

end
