pipeline {
    agent { label 'windows' }

    environment {
        TF_VAR_copy_script = "copy_to_jenkins.sh"
    }

    stages {

        stage('Checkout Repo') {
            steps {
                // 從 GitHub 抓 main branch
                git branch: 'main', 
                    url: 'https://github.com/HarrisonZz/DevSecOps_with_BBB.git'
            }
        }

        stage('Init Terraform (on-premises)') {
            steps {
                dir('Terraform_and_Vagrant/on-premises') {
                    bat '''
                        echo "[INFO] Initialize Terraform..."
                        terraform init -input=false
                    '''
                }
            }
        }

        stage('Plan Infrastructure') {
            steps {
                dir('Terraform_and_Vagrant/on-premises') {
                    bat '''
                        echo "[INFO] Terraform Plan"
                        terraform plan -out=tfplan
                    '''
                }
            }
        }

        stage('Apply Infrastructure') {
            steps {
                dir('Terraform_and_Vagrant/on-premises') {
                    bat '''
                        echo "[INFO] Applying Terraform..."
                        terraform apply -auto-approve tfplan
                    '''
                }
            }
        }

        stage('Cleanup') {
            steps {
                dir('Terraform_and_Vagrant/on-premises') {
                    bat '''
                        echo "[INFO] Cleaning temporary files..."
                        rm -f tfplan
                    '''
                }
            }
        }
    }

    post {
        failure {
            echo "❌ Build failed. Please check logs."
            powershell '''
                Write-Host "Deleting Jenkins workspace: $env:WORKSPACE"
                if (Test-Path $env:WORKSPACE) {
                Remove-Item -Recurse -Force -Path $env:WORKSPACE
                Write-Host "✅ Workspace deleted successfully."
                } else {
                Write-Host "⚠️ No workspace found at $env:WORKSPACE"
                }
            '''
        }
        success {
            echo "✅ Infrastructure successfully deployed."
        }
    }
}
