apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      nodeSelector:
        kubernetes.io/hostname: k3s-controlplane
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
          - tunnel 
          - --no-autoupdate 
          - run 
          - --token 
          - eyJhIjoiY2M2M2YxOTk3YzkxNjc2ZDA0NDExYWYyOTM3YWVjOGMiLCJ0IjoiYzc1YzBjNzctYTEzYy00YTY3LWFjY2MtODAwYzJiZGRlZTQ3IiwicyI6Ik1qZ3pORFppTW1NdFpqWXdOeTAwWkRRd0xUbGtNRFl0WWpKbE9UUTBNREk1TkRWbCJ9
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 300m
            memory: 256Mi
      restartPolicy: Always
