apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-proxy
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-proxy
  template:
    metadata:
      labels:
        app: es-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: es-proxy-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-proxy-conf
  namespace: logging
data:
  default.conf: |
    server {
      listen 8080;
      location / {
        proxy_set_header Authorization "Basic ZWxhc3RpYzpVYWdvaHR2dnZhN1FqVjlJ"; # username:password
        proxy_pass https://elasticsearch-master.logging.svc.cluster.local:9200;
        proxy_ssl_verify off;  # 關閉 CA 驗證（自簽證書會失敗）
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: es-proxy
  namespace: logging
spec:
  ports:
    - port: 9200
      targetPort: 8080
  selector:
    app: es-proxy