apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-proxy
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-proxy
  template:
    metadata:
      labels:
        app: es-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - name: es
              containerPort: 8080   # 對應 ES proxy
            - name: kibana
              containerPort: 8081   # 對應 Kibana proxy
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-conf
          configMap:
            name: es-proxy-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-proxy-conf
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  default.conf: |
    server {
      listen 8080;

      location ~ ^/(_cluster|_cat|_nodes|_tasks) {
        return 403;
      }

      # bulk insert, update
      location ~ ^/.*/_bulk {
        return 403;
      }

      # modify settings or mappings
      location ~ ^/.*/_(settings|mapping|update) {
        return 403;
      }

      location / {
      if ($request_method !~* (GET|HEAD)) {
          return 403;
      }

        proxy_set_header Authorization "Basic ZWxhc3RpYzpVYWdvaHR2dnZhN1FqVjlJ"; # username:password
        proxy_pass https://elasticsearch-master.logging.svc.cluster.local:9200;
        proxy_ssl_verify off;  # 關閉 CA 驗證（自簽證書會失敗）
      }
    }

    server {
      listen 8081;
      location / {
        # 這裡通常不需要額外加 Authorization header，
        # 讓 Kibana 自己處理登入即可
        proxy_pass http://kibana-kibana.logging.svc.cluster.local:5601;

        # 保留一些常見的 header
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: es-proxy
  namespace: logging
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  ports:
    - name: es
      port: 9200        
      targetPort: 8080   
    - name: kibana
      port: 5601         
      targetPort: 8081   
  selector:
    app: es-proxy