apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: {{ include "alertmanager.namespace" . }}
data:
  alertmanager.yml: |
    {{- $smtpSecret := (lookup "v1" "Secret" .Values.smtpPasswordFromSecret.name .Release.Namespace) }}
    {{- if $smtpSecret }}
      {{- $smtpPass := (index $smtpSecret.data .Values.smtpPasswordFromSecret.key | b64dec) }}
      smtp_auth_password: "{{ $smtpPass }}"
    {{- else }}
      smtp_auth_password: "{{ .Values.smtpPassword | default "changeme" }}"
    {{- end }}

    {{- with .Values.config }}
    {{ toYaml . | nindent 4 }}
    {{- end }}

  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
