apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ include "alertmanager.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-9"
{{- $smtpSecret := (lookup "v1" "Secret" .Release.Namespace .Values.smtpPasswordFromSecret.name) }}
{{- $smtpPass := "" }}
{{- if $smtpSecret }}
  {{- $smtpPass = (index $smtpSecret.data .Values.smtpPasswordFromSecret.key | b64dec) }}
{{- else }}
  {{- $smtpPass = (.Values.smtpPassword | default "changeme") }}
{{- end }}
data:
  {{- if .Values.configEnabled }}
  alertmanager.yml: |
{{- $config := deepCopy .Values.config }}
{{- $_ := set $config.global "smtp_auth_password" $smtpPass }}
{{ toYaml $config | indent 4 }}

  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
{{ $value | indent 4 }}
  {{- end }}
  {{- end }}