apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager
  namespace: {{ include "alertmanager.namespace" . }}
{{- $smtpSecret := (lookup "v1" "Secret" .Release.Namespace .Values.smtpPasswordFromSecret.name) }}
{{- $smtpPass := "" }}
{{- if $smtpSecret }}
  {{- $smtpPass = (index $smtpSecret.data .Values.smtpPasswordFromSecret.key | b64dec) }}
{{- else }}
  {{- $smtpPass = (.Values.smtpPassword | default "changeme") }}
{{- end }}
data:
  alertmanager.yml: |
    global:
      smtp_auth_password: "{{ $smtpPass }}"
{{ toYaml .Values.config | indent 4 }}

  {{- range $key, $value := .Values.templates }}
  {{ $key }}: |-
{{ $value | indent 4 }}
  {{- end }}
